kind: ConfigMap
apiVersion: v1
metadata:
  name: orderer-base
  namespace: bc-2nd
  annotations:
    description: ''
data:
  FABRIC_LOGGING_SPEC: info
  ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE: /var/hyperledger/orderer/tls/server.crt
  ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY: /var/hyperledger/orderer/tls/server.key
  ORDERER_GENERAL_CLUSTER_ROOTCAS: '[/var/hyperledger/orderer/tls/ca.crt]'
  ORDERER_GENERAL_GENESISFILE: /var/hyperledger/orderer/orderer.genesis.block
  ORDERER_GENERAL_GENESISMETHOD: file
  ORDERER_GENERAL_LISTENADDRESS: 0.0.0.0
  ORDERER_GENERAL_LOCALMSPDIR: /var/hyperledger/orderer/msp
  ORDERER_GENERAL_LOCALMSPID: OrdererMSP
  ORDERER_GENERAL_TLS_CERTIFICATE: /var/hyperledger/orderer/tls/server.crt
  ORDERER_GENERAL_TLS_ENABLED: 'true'
  ORDERER_GENERAL_TLS_PRIVATEKEY: /var/hyperledger/orderer/tls/server.key
  ORDERER_GENERAL_TLS_ROOTCAS: '[/var/hyperledger/orderer/tls/ca.crt]'
  TZ: Asia/Taipei

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: orderer0-org0
  namespace: bc-2nd
  annotations:
    description: ''
data:
  ORDERER_GENERAL_LISTENPORT: '7050'
  ORDERER_METRICS_PROVIDER: prometheus
  ORDERER_OPERATIONS_LISTENADDRESS: '0.0.0.0:17050'

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: orderer1-org0
  namespace: bc-2nd
  annotations:
    description: ''
data:
  ORDERER_GENERAL_LISTENPORT: '8050'
  ORDERER_METRICS_PROVIDER: prometheus
  ORDERER_OPERATIONS_LISTENADDRESS: '0.0.0.0:18050'

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: orderer2-org0
  namespace: bc-2nd
  annotations:
    description: ''
data:
  ORDERER_GENERAL_LISTENPORT: '9050'
  ORDERER_METRICS_PROVIDER: prometheus
  ORDERER_OPERATIONS_LISTENADDRESS: '0.0.0.0:19050'

---