kind: ConfigMap
apiVersion: v1
metadata:
  name: peer-base
  namespace: bc-2nd
  annotations:
    description: ''
data:
  CORE_PEER_GOSSIP_ORGLEADER: 'false'
  CORE_PEER_GOSSIP_USELEADERELECTION: 'true'
  CORE_PEER_PROFILE_ENABLED: 'true'
  CORE_PEER_TLS_CERT_FILE: /etc/hyperledger/fabric/tls/server.crt
  CORE_PEER_TLS_ENABLED: 'true'
  CORE_PEER_TLS_KEY_FILE: /etc/hyperledger/fabric/tls/server.key
  CORE_PEER_TLS_ROOTCERT_FILE: /etc/hyperledger/fabric/tls/ca.crt
  FABRIC_LOGGING_SPEC: INFO
  TZ: Asia/Taipei

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: peer0-org1
  namespace: bc-2nd
  annotations:
    description: ''
data:
  CORE_METRICS_PROVIDER: prometheus
  CORE_OPERATIONS_LISTENADDRESS: '0.0.0.0:17051'
  CORE_PEER_ADDRESS: 'peer0-org1:7051'
  CORE_PEER_CHAINCODEADDRESS: 'peer0-org1:7052'
  CORE_PEER_CHAINCODELISTENADDRESS: '0.0.0.0:7052'
  CORE_PEER_GOSSIP_BOOTSTRAP: 'peer1-org1:8051'
  CORE_PEER_GOSSIP_EXTERNALENDPOINT: 'peer0-org1:7051'
  CORE_PEER_ID: peer0-org1
  CORE_PEER_LISTENADDRESS: '0.0.0.0:7051'
  CORE_PEER_LOCALMSPID: Org1MSP

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: peer1-org1
  namespace: bc-2nd
  annotations:
    description: ''
data:
  CORE_METRICS_PROVIDER: prometheus
  CORE_OPERATIONS_LISTENADDRESS: '0.0.0.0:18051'
  CORE_PEER_ADDRESS: 'peer1-org1:8051'
  CORE_PEER_CHAINCODEADDRESS: 'peer1-org1:8052'
  CORE_PEER_CHAINCODELISTENADDRESS: '0.0.0.0:8052'
  CORE_PEER_GOSSIP_BOOTSTRAP: 'peer0-org1:7051'
  CORE_PEER_GOSSIP_EXTERNALENDPOINT: 'peer1-org1:8051'
  CORE_PEER_ID: peer1-org1
  CORE_PEER_LISTENADDRESS: '0.0.0.0:8051'
  CORE_PEER_LOCALMSPID: Org1MSP

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: peer0-org2
  namespace: bc-2nd
  annotations:
    description: ''
data:
  CORE_METRICS_PROVIDER: prometheus
  CORE_OPERATIONS_LISTENADDRESS: '0.0.0.0:19051'
  CORE_PEER_ADDRESS: 'peer0-org2:9051'
  CORE_PEER_CHAINCODEADDRESS: 'peer0-org2:9052'
  CORE_PEER_CHAINCODELISTENADDRESS: '0.0.0.0:9052'
  CORE_PEER_GOSSIP_BOOTSTRAP: 'peer1-org2:10051'
  CORE_PEER_GOSSIP_EXTERNALENDPOINT: 'peer0-org2:9051'
  CORE_PEER_ID: peer0-org2
  CORE_PEER_LISTENADDRESS: '0.0.0.0:9051'
  CORE_PEER_LOCALMSPID: Org2MSP

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: peer1-org2
  namespace: bc-2nd
  annotations:
    description: ''
data:
  CORE_METRICS_PROVIDER: prometheus
  CORE_OPERATIONS_LISTENADDRESS: '0.0.0.0:20051'
  CORE_PEER_ADDRESS: 'peer1-org2:10051'
  CORE_PEER_CHAINCODEADDRESS: 'peer1-org2:10052'
  CORE_PEER_CHAINCODELISTENADDRESS: '0.0.0.0:10052'
  CORE_PEER_GOSSIP_BOOTSTRAP: 'peer0-org2:9051'
  CORE_PEER_GOSSIP_EXTERNALENDPOINT: 'peer1-org2:10051'
  CORE_PEER_ID: peer1-org2
  CORE_PEER_LISTENADDRESS: '0.0.0.0:10051'
  CORE_PEER_LOCALMSPID: Org2MSP

---

